/* The following code was generated by JFlex 1.4.3 on 3/12/12 12:16 AM */

package graficacion;

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/12/12 12:16 AM from the specification file
 * <tt>C:/Users/Daniel/Documents/NetBeansProjects/Graficacion/src/graficacion/Comando.flex</tt>
 */
class Autocad implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\2\1\0\1\0\1\1\22\0\1\0\1\0\1\43"+
    "\11\0\1\44\1\40\1\42\1\0\12\41\7\0\1\6\1\37\1\3"+
    "\1\10\1\13\1\0\1\17\1\24\1\16\1\36\1\25\1\21\1\5"+
    "\1\7\1\4\1\22\1\0\1\15\1\26\1\12\1\20\1\23\1\0"+
    "\1\14\1\0\1\35\6\0\1\6\1\37\1\3\1\10\1\30\1\0"+
    "\1\17\1\24\1\27\1\36\1\34\1\21\1\5\1\33\1\4\1\32"+
    "\1\0\1\31\1\11\1\12\1\20\1\23\1\0\1\14\1\0\1\35"+
    "\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\16\1\1\2\4\1\1\3\1\1\1\4\10\0"+
    "\1\5\21\0\1\6\33\0\1\3\5\0\1\7\12\0"+
    "\1\10\1\0\1\11\1\0\1\12\4\0\1\13\10\0"+
    "\1\14\4\0\1\15\3\0\1\16\1\0\1\17\1\20"+
    "\1\21\1\22\6\0\1\23\10\0\1\24\1\0\1\25"+
    "\1\0\1\26\2\0\1\27\6\0\1\30\1\0\1\31"+
    "\1\32\1\33\1\0\1\34\10\0\1\35\1\36\1\0"+
    "\1\37\1\0\2\40\1\41\4\0\1\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\157\0\224\0\271\0\336\0\u0103"+
    "\0\u0128\0\u014d\0\u0172\0\u0197\0\u01bc\0\u01e1\0\u0206\0\u022b"+
    "\0\u0250\0\u0275\0\u029a\0\u02bf\0\u02e4\0\u0309\0\45\0\u032e"+
    "\0\u0353\0\u0378\0\u039d\0\u03c2\0\u03e7\0\u040c\0\u0431\0\45"+
    "\0\u0456\0\u047b\0\u04a0\0\u04c5\0\u04ea\0\u050f\0\u0534\0\u0559"+
    "\0\u057e\0\u05a3\0\u05c8\0\u05ed\0\u0612\0\u0637\0\u065c\0\u0681"+
    "\0\u0309\0\u0309\0\u06a6\0\u06cb\0\u06f0\0\u0715\0\u073a\0\u075f"+
    "\0\u0784\0\u07a9\0\u07ce\0\u07f3\0\u0818\0\u083d\0\u0862\0\u0887"+
    "\0\u08ac\0\u08d1\0\u08f6\0\u091b\0\u0940\0\u0965\0\u098a\0\u09af"+
    "\0\u09d4\0\u09f9\0\u0a1e\0\u0a43\0\u0a68\0\u0681\0\u0a8d\0\u0ab2"+
    "\0\u0ad7\0\u0afc\0\u0b21\0\45\0\u0b46\0\u0b6b\0\u0b90\0\u0bb5"+
    "\0\u0bda\0\u0bff\0\u0c24\0\u0c49\0\u0c6e\0\u0c93\0\45\0\u0cb8"+
    "\0\45\0\u0cdd\0\45\0\u0d02\0\u0d27\0\u0d4c\0\u0d71\0\45"+
    "\0\u0d96\0\u0dbb\0\u0de0\0\u0e05\0\u0e2a\0\u0e4f\0\u0e74\0\u0e99"+
    "\0\45\0\u0ebe\0\u0ee3\0\u0f08\0\u0f2d\0\45\0\u0f52\0\u0f77"+
    "\0\u0f9c\0\45\0\u0fc1\0\45\0\45\0\45\0\45\0\u0fe6"+
    "\0\u100b\0\u1030\0\u1055\0\u107a\0\u109f\0\45\0\u10c4\0\u10e9"+
    "\0\u110e\0\u1133\0\u1158\0\u117d\0\u11a2\0\u11c7\0\45\0\u11ec"+
    "\0\45\0\u1211\0\45\0\u1236\0\u125b\0\45\0\u1280\0\u12a5"+
    "\0\u12ca\0\u12ef\0\u1314\0\u1339\0\45\0\u135e\0\45\0\45"+
    "\0\45\0\u1383\0\45\0\u13a8\0\u13cd\0\u13f2\0\u1417\0\u143c"+
    "\0\u1461\0\u1486\0\u14ab\0\45\0\45\0\u14d0\0\45\0\u14f5"+
    "\0\45\0\u151a\0\45\0\u153f\0\u1564\0\u1589\0\u15ae\0\45";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\2\2\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\2\1\13\1\14\1\15\1\2"+
    "\1\16\1\17\1\20\1\2\1\21\1\22\1\14\1\12"+
    "\1\13\1\17\1\6\1\21\2\2\1\23\1\24\1\25"+
    "\1\2\1\26\1\27\47\0\1\2\46\0\1\30\11\0"+
    "\1\31\1\0\1\32\6\0\1\31\22\0\1\33\11\0"+
    "\1\34\15\0\1\35\15\0\1\36\4\0\1\37\7\0"+
    "\1\40\4\0\1\37\27\0\1\41\14\0\1\41\27\0"+
    "\1\42\2\0\1\43\10\0\1\43\1\42\27\0\1\44"+
    "\1\0\1\45\12\0\1\44\1\45\24\0\1\46\14\0"+
    "\1\46\22\0\1\47\45\0\1\50\54\0\1\51\13\0"+
    "\1\51\31\0\1\52\10\0\1\52\35\0\1\53\42\0"+
    "\1\54\10\0\1\54\21\0\1\55\53\0\1\42\2\0"+
    "\1\43\10\0\1\56\1\42\35\0\1\57\64\0\1\25"+
    "\44\0\1\25\1\60\2\0\2\61\1\0\40\61\1\62"+
    "\1\61\5\0\1\63\54\0\1\64\13\0\1\64\21\0"+
    "\1\65\44\0\1\66\53\0\1\67\2\0\1\67\10\0"+
    "\1\67\33\0\1\70\41\0\1\71\13\0\1\71\32\0"+
    "\1\72\36\0\1\73\14\0\1\73\37\0\1\74\36\0"+
    "\1\75\14\0\1\75\30\0\1\76\36\0\1\77\7\0"+
    "\1\100\10\0\1\100\20\0\1\101\52\0\1\102\1\103"+
    "\13\0\1\102\7\0\1\104\14\0\1\105\54\0\1\106"+
    "\10\0\1\106\24\0\1\107\1\0\1\110\14\0\1\110"+
    "\4\0\1\107\20\0\1\111\23\0\1\111\22\0\1\112"+
    "\14\0\1\112\21\0\1\113\54\0\1\75\14\0\1\114"+
    "\22\0\1\115\77\0\1\116\11\0\1\117\41\0\1\120"+
    "\51\0\1\121\51\0\1\122\13\0\1\122\35\0\1\123"+
    "\7\0\1\123\33\0\1\124\31\0\1\125\53\0\1\126"+
    "\13\0\1\126\21\0\1\127\15\0\1\130\33\0\1\131"+
    "\14\0\1\131\31\0\1\132\13\0\1\132\25\0\1\133"+
    "\43\0\1\134\14\0\1\134\24\0\1\135\44\0\1\136"+
    "\44\0\1\137\44\0\1\140\42\0\1\141\57\0\1\142"+
    "\36\0\1\143\14\0\1\143\31\0\1\144\14\0\1\144"+
    "\26\0\1\145\44\0\1\146\44\0\1\147\56\0\1\150"+
    "\35\0\1\132\13\0\1\151\22\0\1\152\23\0\1\152"+
    "\20\0\1\153\23\0\1\153\31\0\1\154\41\0\1\155"+
    "\13\0\1\155\31\0\1\156\10\0\1\156\23\0\1\157"+
    "\45\0\1\160\23\0\1\160\15\0\1\161\57\0\1\162"+
    "\33\0\1\163\41\0\1\164\63\0\1\165\7\0\1\165"+
    "\16\0\1\166\61\0\1\167\32\0\1\170\23\0\1\170"+
    "\32\0\1\171\40\0\1\172\13\0\1\172\26\0\1\173"+
    "\14\0\1\173\22\0\1\174\44\0\1\175\42\0\1\176"+
    "\46\0\1\177\60\0\1\165\7\0\1\200\15\0\1\201"+
    "\51\0\1\202\55\0\1\203\31\0\1\204\57\0\1\205"+
    "\40\0\1\206\13\0\1\206\51\0\1\207\23\0\1\210"+
    "\13\0\1\210\16\0\1\211\44\0\1\212\57\0\1\213"+
    "\10\0\1\213\23\0\1\214\55\0\1\215\33\0\1\216"+
    "\45\0\1\217\23\0\1\217\27\0\1\213\10\0\1\220"+
    "\21\0\1\221\44\0\1\222\44\0\1\223\50\0\1\224"+
    "\55\0\1\225\31\0\1\226\56\0\1\227\37\0\1\230"+
    "\14\0\1\230\32\0\1\231\10\0\1\231\24\0\1\232"+
    "\23\0\1\232\21\0\1\233\54\0\1\234\41\0\1\235"+
    "\13\0\1\235\22\0\1\232\23\0\1\236\22\0\1\237"+
    "\14\0\1\237\22\0\1\240\44\0\1\241\62\0\1\242"+
    "\7\0\1\242\27\0\1\243\13\0\1\243\17\0\1\244"+
    "\51\0\1\245\14\0\1\245\24\0\1\246\57\0\1\247"+
    "\34\0\1\250\14\0\1\245\24\0\1\251\45\0\1\252"+
    "\23\0\1\252\36\0\1\253\6\0\1\253\25\0\1\254"+
    "\13\0\1\254\17\0\1\255\65\0\1\253\6\0\1\256"+
    "\25\0\1\257\13\0\1\257\21\0\1\260\54\0\1\261"+
    "\10\0\1\261\33\0\1\261\10\0\1\262\32\0\1\263"+
    "\13\0\1\263\16\0\1\264\45\0\1\265\61\0\1\266"+
    "\27\0\1\267\55\0\1\270\13\0\1\270\13\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5587];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\24\1\1\11\10\0\1\11\21\0\1\1"+
    "\33\0\1\1\5\0\1\11\12\0\1\11\1\0\1\11"+
    "\1\0\1\11\4\0\1\11\10\0\1\11\4\0\1\11"+
    "\3\0\1\11\1\0\4\11\6\0\1\11\10\0\1\11"+
    "\1\0\1\11\1\0\1\11\2\0\1\11\6\0\1\11"+
    "\1\0\3\11\1\0\1\11\10\0\2\11\1\0\1\11"+
    "\1\0\1\11\1\1\1\11\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Autocad(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Autocad(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 142) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 19: 
          { return new Symbol (sym.AGRUPAR, yyline, yycolumn );
          }
        case 35: break;
        case 32: 
          { return new Symbol (sym.SIERPINSKI, yyline, yycolumn );
          }
        case 36: break;
        case 25: 
          { return new Symbol (sym.COMANDO, yyline, yycolumn );
          }
        case 37: break;
        case 7: 
          { return new Symbol (sym.AZUL, yyline, yycolumn );
          }
        case 38: break;
        case 4: 
          { return new Symbol (sym.COMA, yyline, yycolumn );
          }
        case 39: break;
        case 3: 
          { return new Symbol(sym.NUMERO, yyline, yycolumn, new Double(yytext())  );
          }
        case 40: break;
        case 2: 
          { return new Symbol (sym.V, yyline, yycolumn );
          }
        case 41: break;
        case 8: 
          { return new Symbol (sym.ROSA, yyline, yycolumn );
          }
        case 42: break;
        case 31: 
          { return new Symbol (sym.DESAGRUPAR, yyline, yycolumn );
          }
        case 43: break;
        case 21: 
          { return new Symbol (sym.BLANCO, yyline, yycolumn );
          }
        case 44: break;
        case 17: 
          { return new Symbol (sym.PUNTO, yyline, yycolumn );
          }
        case 45: break;
        case 30: 
          { return new Symbol (sym.TRIANGULO, yyline, yycolumn );
          }
        case 46: break;
        case 5: 
          { return new Symbol (sym.NV, yyline, yycolumn );
          }
        case 47: break;
        case 28: 
          { return new Symbol (sym.DESHACER, yyline, yycolumn );
          }
        case 48: break;
        case 6: 
          { return new Symbol(sym.CADENA, yyline, yycolumn, new String(yytext().substring(1, yytext().length() - 1)));
          }
        case 49: break;
        case 12: 
          { return new Symbol (sym.NEGRO, yyline, yycolumn );
          }
        case 50: break;
        case 26: 
          { return new Symbol (sym.CUADRADO, yyline, yycolumn );
          }
        case 51: break;
        case 34: 
          { return new Symbol (sym.COLOR, yyline, yycolumn );
          }
        case 52: break;
        case 23: 
          { return new Symbol (sym.NARANJA, yyline, yycolumn );
          }
        case 53: break;
        case 14: 
          { return new Symbol (sym.ROTAR, yyline, yycolumn );
          }
        case 54: break;
        case 22: 
          { return new Symbol (sym.CIRCULO, yyline, yycolumn );
          }
        case 55: break;
        case 15: 
          { return new Symbol (sym.LINEA, yyline, yycolumn );
          }
        case 56: break;
        case 27: 
          { return new Symbol (sym.AMARILLO, yyline, yycolumn );
          }
        case 57: break;
        case 16: 
          { return new Symbol (sym.LISTA, yyline, yycolumn );
          }
        case 58: break;
        case 18: 
          { return new Symbol (sym.VISTA, yyline, yycolumn );
          }
        case 59: break;
        case 9: 
          { return new Symbol (sym.ROJO, yyline, yycolumn );
          }
        case 60: break;
        case 11: 
          { return new Symbol (sym.KOCH, yyline, yycolumn );
          }
        case 61: break;
        case 29: 
          { return new Symbol (sym.TRASLADAR, yyline, yycolumn );
          }
        case 62: break;
        case 24: 
          { return new Symbol (sym.ESCALAR, yyline, yycolumn );
          }
        case 63: break;
        case 10: 
          { return new Symbol (sym.GRIS, yyline, yycolumn );
          }
        case 64: break;
        case 33: 
          { return new Symbol (sym.SELECCIONAR, yyline, yycolumn );
          }
        case 65: break;
        case 20: 
          { return new Symbol (sym.IMAGEN, yyline, yycolumn );
          }
        case 66: break;
        case 1: 
          { 
          }
        case 67: break;
        case 13: 
          { return new Symbol (sym.TEXTO, yyline, yycolumn );
          }
        case 68: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
