
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 04 12:29:37 CST 2012
//----------------------------------------------------

package graficacion;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GRIS = 31;
  public static final int LINEA = 7;
  public static final int ESCALAR = 18;
  public static final int IMAGEN = 11;
  public static final int VISTA = 16;
  public static final int PUNTO = 9;
  public static final int CADENA = 3;
  public static final int KOCH = 21;
  public static final int V = 23;
  public static final int ROTAR = 20;
  public static final int DESAGRUPAR = 5;
  public static final int AGRUPAR = 4;
  public static final int BLANCO = 33;
  public static final int COLOR = 26;
  public static final int CUADRADO = 10;
  public static final int ROJO = 28;
  public static final int AMARILLO = 32;
  public static final int SIERPINSKI = 22;
  public static final int COMA = 13;
  public static final int COMANDO = 14;
  public static final int EOF = 0;
  public static final int TEXTO = 2;
  public static final int NV = 24;
  public static final int error = 1;
  public static final int NUMERO = 12;
  public static final int CIRCULO = 8;
  public static final int ROSA = 34;
  public static final int AZUL = 27;
  public static final int TRASLADAR = 19;
  public static final int TRIANGULO = 6;
  public static final int LISTA = 15;
  public static final int NEGRO = 29;
  public static final int NARANJA = 30;
  public static final int SELECCIONAR = 17;
  public static final int DESHACER = 25;
}

